<stream title="feat_5ivesta_family_newyear" url="http://newyear.url.ph/uploads/23_45_feat_5ivesta_family_newyear.mp3" />
<stream title="ABBA_Happy_New_Year" url="http://newyear.url.ph/uploads/ABBA_Happy_New_Year.mp3" />
<stream title="Виктория_Дайнеко_и_Корни_Ну_а_он_уже_наступает_В_наш_дом" url="http://newyear.url.ph/uploads/Виктория_Дайнеко_и_Корни_Ну_а_он_уже_наступает_В_н.mp3" />
<stream title="Вирус_Новый_год" url="http://newyear.url.ph/uploads/Вирус_Новый_год.mp3" />
<stream title="Григорий_Лепс_Новый_год_Рюмка_водки_на_столе" url="http://newyear.url.ph/uploads/Григорий_Лепс_Новый_год_2012_Рюмка_водки_на_столе.mp3" />
<stream title="Дима_Билан_Новый_Год_С_Новой_Строчки_Ночь_двенадцать" url="http://newyear.url.ph/uploads/Дима_Билан_Новый_Год_С_Новой_Строчки_Ночь_двенадца.mp3" />
<stream title="Дискотека_Авария_Новый_год_к_нам_мчится" url="http://newyear.url.ph/uploads/Дискотека_Авария_Новый_год_к_нам_мчится.mp3" />
<stream title="Катя_Лель_Новый_Год" url="http://newyear.url.ph/uploads/Катя_Лель_Новый_Год.mp3" />
<stream title="Новогодняя_скоро_новый_2014_год_" url="http://newyear.url.ph/uploads/Новогодняя_скоро_новый_2012_год_.mp3" />
<stream title="Новый_год_Российский_дед_мороз" url="http://newyear.url.ph/uploads/Новый_год_Российский_дед_мороз.mp3" />
<stream title="Нюша_Это_Новый_Год" url="http://newyear.url.ph/uploads/Нюша_Это_Новый_Год.mp3" />
<stream title="ОПА_ГАНГНАМ_СТАЙЛ_Это_Новый_Год" url="http://newyear.url.ph/uploads/ОПА_ГАНГНАМ_СТАЙЛ_Это_Новый_Год.mp3" />
<stream title="Тамерлан_и_Алена_Омаргалиева_Новогодняя_Загадай_своё_желание" url="http://newyear.url.ph/uploads/Тамерлан_и_Алена_Омаргалиева_Новогодняя_Загадай_св.mp3" />
<stream title="Тутси_100_Свечей_Новый_Год" url="http://newyear.url.ph/uploads/Тутси_100_Свечей_Новый_Год_.mp3" />
<stream title="Фабрика_Звезд_3_С_Новым_годом_Снегом_белым_всё_замело" url="http://newyear.url.ph/uploads/Фабрика_Звезд_3_С_Новым_годом_Снегом_белым_вс_заме.mp3" />
<stream title="Новогодняя" url="http://newyear.url.ph/uploads/Эту_песню_мы_пели_на_новый_год_в_1_классе_новогодн.mp3" />
<stream title="Юля_Савичева_Новый_Год" url="http://newyear.url.ph/uploads/Юля_Савичева_Новый_Год.mp3" />